version: '3'
services:
  api:
    build: app
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      - redis
      - elasticsearch

  db:
    image: postgres:latest
    env_file: .env
    volumes:
      - empty_project_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DBNAME}


  redis:
    image: 'redis:7.0-alpine'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=/.*/
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
    volumes:
      - elastic_elastic_data:/usr/share/elasticsearch/data


volumes:
  empty_project_postgres_data:
    external: true
  redis_data:
  elastic_elastic_data:
    external: true
